name: Build Geode Mod

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android
            target: Android
            cli-args: "--target android64"

    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Android NDK
        if: matrix.config.target == 'Android'
        uses: nndst/setup-android-ndk@v1
        with:
          ndk-version: r26b

      - name: Setup Geode CLI
        uses: geode-sdk/cli-action@v2
        with:
          geode-version: stable

      - name: Build Mod
        run: |
          geode package build . ${{ matrix.config.cli-args }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.name }}
          path: .geode-build/*.geode
